language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env: MINIMUM_VERSIONS=false

os: linux
dist: bionic

php:
  - 7.4
  - 8.0
  - 8.1

install:
  - if [[ $MINIMUM_VERSIONS = false ]]; then composer install; fi
  - if [[ $MINIMUM_VERSIONS = true ]]; then composer update --no-interaction --prefer-lowest; fi

jobs:
  include:
    - stage: style check
      script: composer run style:check