<?php

namespace Amo\Sdk\Service;

use Amo\Sdk\AmoClient;
use Amo\Sdk\Models\Subject;
use Amo\Sdk\Service\TeamService;

class SubjectService extends AbstractService
{
    protected ?string $subjectId;

    public function __invoke(AmoClient $apiClient, string $subjectId = null): AbstractService
    {
        $this->subjectId = $subjectId;
        return parent::__invoke($apiClient); // TODO: Change the autogenerated stub
    }

    public function create(Subject $subject): Subject
    {
        $resp = $this->apiClient->post($this->subjectUrl(), [
            'body' => $subject,
        ]);

        return Subject::fromStream($resp->getBody());
    }

    /**
     * @return string
     */
    private function subjectUrl(): string
    {
        $url = '/subjects';

        if ($this->subjectId) {
            $url .= '/' . $this->subjectId;
        }

        return $url;
    }
}